image:
  file: gitpod.Dockerfile
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - redhat.vscode-commons
    - redhat.vscode-xml
    - visualstudioexptteam.vscodeintellicode
